services:
  asdoria_sylius_locale_switcher_plugin.controller.locale_switcher:
    public: true
    class: Asdoria\SyliusLocaleSwitcherPlugin\Controller\LocaleSwitcherController
    decorates: 'sylius.controller.shop.locale_switch'
    arguments:
      $baseLocaleSwitchController: '@asdoria_sylius_locale_switcher_plugin.controller.locale_switcher.inner'
      $templatingEngine: '@twig'
      $localeContext: '@sylius.context.locale'
      $localeProvider: '@sylius.locale_provider'
      $metadataRegistry: '@sylius.resource_registry'
      $requestStack: '@request_stack'
      $requestConfigurationFactory: '@sylius.resource_controller.request_configuration_factory'
      $resourceGuesserRegistry: '@asdoria_sylius_locale_switcher_plugin.resource_guesser_service_registry'
